# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Package Version

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: git config --global user.email "kananivinit97@gmail.com"
      - run: git config --global user.name "Vinit Kanani"
      - run: git config user.email "kananivinit97@gmail.com"
      - run: git config user.name "Vinit Kanani"
      - run: npm i
      - run: printenv
      - run: npm run deploy
      - run: npm version patch
      - run: git push
      - run: git push --tags
      - run: npm ci
        if: always()
      - run: npm test
      - uses: codecov/codecov-action@v1

